import { CheckCircle2, Instagram, Mail, MapPin, Phone } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { images } from "@/content/farmData";
import { Reveal, SectionHeading } from "./shared";

const inputClass = "h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition-shadow placeholder:text-muted-foreground focus:ring-2 focus:ring-ring";

export function Contact() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <>
    <section id="contact" className="px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><Reveal><SectionHeading eyebrow="The road out is worth it" title="Find Your Way to The Banyan" intro="We’re tucked away in the countryside, close enough for a weekend and far enough to feel like an escape." /></Reveal>
      <div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><Reveal><div className="flex h-full flex-col overflow-hidden rounded-2xl bg-primary text-primary-foreground"><div className="relative min-h-72 flex-1"><img src={images.sunset} alt="Countryside path to The Banyan Farms" width={1000} height={800} loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-75"/><div className="absolute inset-0 bg-primary/20"/><div className="absolute inset-5 grid place-items-center rounded-xl border border-primary-foreground/30"><div className="rounded-full bg-cream p-4 text-primary shadow-xl"><MapPin className="size-7"/></div></div></div><div className="space-y-4 p-7"><p className="flex gap-3 text-sm"><MapPin className="size-5 shrink-0 text-accent"/> Countryside location, India — exact address coming soon</p><p className="flex gap-3 text-sm"><Phone className="size-5 shrink-0 text-accent"/> +91 XXXXX XXXXX</p><p className="flex gap-3 text-sm"><Mail className="size-5 shrink-0 text-accent"/> hello@thebanyanfarms.com</p><p className="flex gap-3 text-sm"><Instagram className="size-5 shrink-0 text-accent"/> @thebanyanfarms</p></div></div></Reveal>
      <Reveal><div className="rounded-2xl border border-border bg-card p-6 shadow-sm md:p-8">{sent ? <div className="grid min-h-[34rem] place-items-center text-center"><div><CheckCircle2 className="mx-auto size-14 text-primary"/><h3 className="mt-5 font-serif text-4xl">Your escape starts here.</h3><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Thanks for your enquiry. This demo doesn’t send messages yet, but your form experience is ready.</p><Button className="mt-6" variant="outline" onClick={() => setSent(false)}>Send another enquiry</Button></div></div> : <form onSubmit={submit}><h3 className="font-serif text-3xl">Tell us about your trip</h3><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Name<input required name="name" placeholder="Your name" className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold">Phone<input required name="phone" type="tel" placeholder="Your phone" className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold">Email<input required name="email" type="email" placeholder="you@email.com" className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold">Number of Guests<input required name="guests" type="number" min="1" placeholder="2" className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold">Preferred Date<input required name="date" type="date" className={`${inputClass} mt-2`} /></label><label className="text-xs font-bold">Stay Type<select required name="stay" className={`${inputClass} mt-2`} defaultValue=""><option value="" disabled>Select an option</option><option>Day Escape</option><option>Farm Weekend</option><option>Adventure Night</option><option>Other</option></select></label></div><label className="mt-4 block text-xs font-bold">Message<textarea name="message" rows={5} placeholder="Anything we should know?" className="mt-2 w-full rounded-xl border border-border bg-background p-4 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" /></label><Button type="submit" size="lg" className="mt-5 w-full sm:w-auto">Send Enquiry</Button></form>}</div></Reveal></div>
    </div></section>
  </>;
}